add search to filter
ForomePlatform/Anfisa-React-Client pull request #112
Opened 2021-08-11 10:11 UTC by Lapk1n

2021-08-11 11:03 UTC, Ellerage requested changes

2021-08-11 11:03 UTC, Ellerage commented on src/pages/filter/ui/filter-refiner-groups.tsx
> +    parent?.addEventListener('DOMSubtreeModified', () => {
Не уверен, что это нужно

2021-08-11 11:03 UTC, Ellerage commented on src/pages/filter/ui/filter-refiner-groups.tsx
> +            {values[index]
Можно вынести логику фильтрации в геттер в mobx сторе, например как в списке датасетов ( src/store/dirinfo.ts )

2021-08-11 12:00 UTC, Hellek commented on src/components/input-search.tsx
> +        style={{ outline: filter ? 'none' : undefined }}
`className={cn({ "outline-none": filter })}`
Если в значении true, то добавляется название свойства

2021-08-11 12:54 UTC, Lapk1n commented on src/components/input-search.tsx
> +        style={{ outline: filter ? 'none' : undefined }}
Ни outline-none ни focus:outline-none ни другие решения из https://github.com/tailwindlabs/tailwindcss/issues/1231 не удаляют outline

2021-08-11 13:25 UTC, Hellek commented on src/components/input-search.tsx
> +  const { className, style, filter, ...tempRest } = rest
Предлагаю вообще убрать эти стили, т.к. есть сразу ряд вопросов
- почему именно 95%?
- почему левый отступ задаётся в родителе, а правый отступ внутри компонента за счёт уменьшения его ширины?

Предлагаю убрать вообще стили из этого компонента, а в родителе сделать так
```
<div id="input" className="mx-4 mb-3">
  <InputSearch
    placeholder={t('filter.searchForAField')}
    value={datasetStore.searchField}
    filter
    onChange={e => {
      datasetStore.addSearchField(e.target.value)
    }}
  />
</div>
```

2021-08-11 13:26 UTC, Hellek commented on src/components/input-search.tsx
> +  const { className, style, filter, ...tempRest } = rest
И отступы по краям будут одинаковые
![image](https://user-images.githubusercontent.com/7388712/129037141-2aa733b0-885f-4792-8d62-c852589bf399.png)

2021-08-12 16:16 UTC, Hellek commented on src/components/input-search.tsx
> +  const { className, style, filter, ...tempRest } = rest
Этот компонент используется в 3 местах и нигде не используется style. К тому же и в будущем, было бы круто, не использовать хардкод через стили. Может тогда и проас стоит убрать (и из интерфейса тоже)?

2021-08-13 09:50 UTC, merged