Forome 301
ForomePlatform/Anfisa-React-Client pull request #249
Opened 2021-11-29 16:20 UTC by evgeniy-chernomortsev

2021-11-30 09:18 UTC, YaroslavTrefilovBraveDevelopers approved these changes

2021-11-30 09:56 UTC, Lapk1n requested changes

2021-11-30 09:56 UTC, Lapk1n commented on src/components/variant/ui/header.tsx
> +      // setVariantIndex()
Пригодится в  будущем?

2021-11-30 09:56 UTC, Lapk1n commented on src/pages/filter/page.tsx
> -        filterStore.resetData()
Эти ресеты добавлял не случайно. Попробуй открыть в dtree xl_PGP3140_wgs_NIST-4_2 затем с помощью крестика в правом верхнем углу dtree закрыть его и затем отркыть PGP3140_wgs_panel_hl. Кол-во вариантов на самом дереве не меняются
<img width="985" alt="Screenshot 2021-11-30 at 13 24 04" src="https://user-images.githubusercontent.com/74919871/144020369-af1655c8-75ea-4476-b2ef-85974cf77b71.png">

2021-11-30 09:56 UTC, Lapk1n commented on src/pages/filter/page.tsx
> -        filterStore.resetData()
тотал в шапке 5кк+, в дереве 2к+

2021-11-30 10:24 UTC, Hellek commented on tsconfig.extend.json
> +      "@glb/*": ["./glb/*"],
Видел выше в файла, где без алиаса было, раз он есть, лучше везде использовать

2021-12-02 07:45 UTC, Lapk1n approved these changes

2021-12-02 08:29 UTC, merged