fix(FOROME-397) fix filter tags section variants with notes option
ForomePlatform/Anfisa-React-Client pull request #334
Opened 2022-01-10 16:57 UTC by evgeniy-chernomortsev

2022-01-10 22:28 UTC, AndreyUstyumenko commented on src/pages/ws/ui/control-panel-filter-tags.tsx
> +        [...toJS(zoneStore.selectedTags), '_note'],
no need to use toJS.

2022-01-11 08:37 UTC, evgeniy-chernomortsev commented on src/pages/ws/ui/control-panel-filter-tags.tsx
> +        [...toJS(zoneStore.selectedTags), '_note'],
+

2022-01-11 08:41 UTC, AndreyUstyumenko approved these changes

2022-01-11 11:43 UTC, Lapk1n requested changes
1. Open PGP3140_wgs_panel
2. Choose variants with notes only
3. Main table displays 7 variants
The 4th variant doesn't have notes inside

2022-01-11 12:27 UTC, evgeniy-chernomortsev commented
> 1. Open PGP3140_wgs_panel
> 2. Choose variants with notes only
> 3. Main table displays 7 variants
>    The 4th variant doesn't have notes inside

these 7 variants we are getting from back-end putting string "_note" to api request (not filtering list manually), so maybe we should check this case on back-end at first?

2022-01-11 14:26 UTC, Lapk1n approved these changes

2022-01-12 08:35 UTC, YaroslavTrefilovBraveDevelopers approved these changes

2022-01-12 10:48 UTC, merged