fix(FOROME-698): remove empty space
ForomePlatform/Anfisa-React-Client pull request #458
Opened 2022-03-01 09:50 UTC by QSdmitrioul

https://quantori.atlassian.net/browse/FOROME-698

2022-03-01 11:43 UTC, AlMaQntr approved these changes

2022-03-01 13:31 UTC, YaroslavTrefilovBraveDevelopers requested changes

2022-03-01 13:31 UTC, YaroslavTrefilovBraveDevelopers commented on src/pages/filter/ui/query-builder/groups/query-builder-groups.tsx
>            className="overflow-y-auto"
This fix affects "Decision Tree".  The bottom chart is not fully loaded

Before fix:
![image](https://user-images.githubusercontent.com/87524295/156177504-2b73849f-47e0-4b55-aa78-703e327c36ac.png)

After fix:
![image](https://user-images.githubusercontent.com/87524295/156177999-f7f5b714-ae87-41c1-a500-4bbf16a7e3f3.png)

2022-03-02 07:33 UTC, QSdmitrioul commented on src/pages/filter/ui/query-builder/groups/query-builder-groups.tsx
>            className="overflow-y-auto"
[Fixed](https://github.com/ForomePlatform/Anfisa-React-Client/pull/458/commits/45cbfee94440c67fdcbf83fc2b8ec53ad95c5dfb)

2022-03-03 20:58 UTC, AndreyUstyumenko approved these changes

2022-03-05 14:17 UTC, merged