refactor(FOROME-724): compound het
ForomePlatform/Anfisa-React-Client pull request #474
Opened 2022-03-11 08:54 UTC by Lapk1n

https://quantori.atlassian.net/browse/FOROME-724

PR into refactor/FOROME-723

2022-03-15 07:13 UTC, YaroslavTrefilovBraveDevelopers approved these changes

2022-03-15 20:33 UTC, AndreyUstyumenko commented on src/pages/filter/ui/modal-edit/components/modal-compound-het/modal-compound-het.tsx
> +    dtreeStore.fetchStatFuncAsync(groupName, params)
useEffect content should be in store, just call a method from there

2022-03-16 12:36 UTC, AndreyUstyumenko approved these changes

2022-03-18 05:08 UTC, AlMaQntr requested changes

2022-03-18 05:08 UTC, AlMaQntr commented on src/pages/filter/ui/modal-edit/modal-edit.store.ts
> +      subGroup.find((item, currNo) => {
The `find` method returns found element, try use it (e.g. `const group = subGroup.find(item => item.name === this.groupName)`)

Also, converting `stat-list` to dictionary is note required here. 
You can just iterate over `stat-list` to find the group.
`return dtreeStore.startDtreeStat['stat-list'].find(item => item.name === this.groupName)?.family ?? []`

2022-03-18 05:08 UTC, AlMaQntr commented on src/pages/filter/ui/modal-edit/modal-edit.store.ts
> +  public get approxModes() {
And here you can also iterate over `stat-list`.
By the way, i think that you can create getter for getting current item from `stat-list`

2022-03-18 07:04 UTC, closed without merging