fix(FOROME-560): dtree variant numbers separated by commas
ForomePlatform/Anfisa-React-Client pull request #490
Opened 2022-03-17 09:15 UTC by QSdmitrioul

https://quantori.atlassian.net/jira/software/c/projects/FOROME/boards/122?modal=detail&selectedIssue=FOROME-560&assignee=612900330952180069060410

2022-03-17 12:07 UTC, YaroslavTrefilovBraveDevelopers commented
The application crashes if the tree page reloads the page

2022-03-17 12:08 UTC, YaroslavTrefilovBraveDevelopers requested changes
The application crashes if the tree page reloads the page

2022-03-18 08:29 UTC, YaroslavTrefilovBraveDevelopers approved these changes

2022-03-18 15:09 UTC, Lapk1n approved these changes

2022-03-23 07:49 UTC, merged