fix(FOROME-785): add set all and reset all buttons in inheritance mode
ForomePlatform/Anfisa-React-Client pull request #510
Opened 2022-03-24 15:57 UTC by QSdmitrioul

https://quantori.atlassian.net/browse/FOROME-785

2022-03-24 22:50 UTC, AndreyUstyumenko commented on src/pages/filter/ui/modal-edit/components/modal-inheritance-mode/components/inheritance-mode-content.tsx
> +    const selectAll = setAll(true)
1. Move this logic to ModalInheritanceModeStore
2. Don't use currying where it's not needed, keep the code as obvious as possible

2022-03-25 05:27 UTC, Lapk1n commented
The "Reset" button on the right side of the problem groups block must reset selected filters below too (just like the clear all button) because we can't allow users to create inh_mode filter without problem group/groups selected

2022-03-25 05:28 UTC, Lapk1n requested changes
The "Reset" button on the right side of the problem groups block must reset selected filters below too (just like the clear all button) because we can't allow users to create inh_mode filter without problem group/groups selected

2022-03-25 12:49 UTC, YaroslavTrefilovBraveDevelopers approved these changes

2022-03-25 21:51 UTC, AndreyUstyumenko approved these changes

2022-03-28 09:52 UTC, Lapk1n approved these changes

2022-03-28 13:15 UTC, merged