fix(FOROME-760): remove exception on opening view variants
ForomePlatform/Anfisa-React-Client pull request #511
Opened 2022-03-24 16:09 UTC by QSdmitrioul

https://quantori.atlassian.net/browse/FOROME-760

2022-03-24 22:43 UTC, AndreyUstyumenko approved these changes

2022-03-25 05:39 UTC, Lapk1n requested changes
The bug is still reproduced.

https://user-images.githubusercontent.com/74919871/160061088-5d65b22f-f673-4191-be47-b2a69dd3e49c.mov

2022-03-25 21:52 UTC, AndreyUstyumenko approved these changes

2022-03-27 16:15 UTC, YaroslavTrefilovBraveDevelopers approved these changes

2022-03-28 09:50 UTC, Lapk1n approved these changes

2022-03-28 13:19 UTC, merged