fix(FOROME-833): don't delete columns after hiding them in column lis…
ForomePlatform/Anfisa-React-Client pull request #550
Opened 2022-04-07 14:20 UTC by QSdmitrioul

…t for setting table
https://quantori.atlassian.net/browse/FOROME-833

2022-04-07 15:59 UTC, AndreyUstyumenko approved these changes

2022-04-11 07:08 UTC, QYaroslavTrefilov requested changes
In a modal window, the column order is not reset even if we click the "Cancel" button


https://user-images.githubusercontent.com/102788634/162683383-bffa443f-8164-4ce9-ae4b-1f45c89570f3.mp4

2022-04-11 07:26 UTC, QSdmitrioul commented
> In a modal window, the column order is not reset even if we click the "Cancel" button
> 
>  bag11april.mp4

It looks like a different bug from

2022-04-11 11:17 UTC, QYaroslavTrefilov approved these changes

2022-04-11 11:36 UTC, merged