fix(FOROME-872): get new variant list  after change dataset
ForomePlatform/Anfisa-React-Client pull request #574
Opened 2022-04-19 11:57 UTC by QYaroslavTrefilov

https://quantori.atlassian.net/browse/FOROME-872

2022-04-19 13:11 UTC, AndreyUstyumenko approved these changes

2022-04-22 04:19 UTC, AlMaQntr commented
I think, we should recheck this issue, some code in this PR is obsolete

2022-04-22 04:22 UTC, AlMaQntr requested changes
I think, we should recheck this issue, some code in this PR is obsolete

2022-04-22 14:06 UTC, Lapk1n approved these changes

2022-04-25 08:47 UTC, QYaroslavTrefilov commented
Changes made before were not relevant. Instead of creating a new PR, I decided to rebase to the end of the develop branch. After the push, I realized that I probably erased the history of past commits in vain.

2022-04-25 17:21 UTC, AndreyUstyumenko approved these changes

2022-04-26 15:12 UTC, Lapk1n approved these changes

2022-04-29 05:00 UTC, AlMaQntr approved these changes

2022-04-29 06:57 UTC, merged