feat(FOROME-994): split enum modal and panel into one component
ForomePlatform/Anfisa-React-Client pull request #629
Opened 2022-05-12 08:54 UTC by Lapk1n

https://quantori.atlassian.net/browse/FOROME-994

In addition:
1. Fixed FR tree layout

2022-05-13 05:00 UTC, AlMaQntr requested changes

2022-05-13 05:00 UTC, AlMaQntr commented on src/pages/filter/common/attributes/attribute.store.ts
> +    return filterStore.method === GlbPagesNames.Refiner
Can we avoid to use `filterStore.method` for page detecting?
I think, we can some base store and extend it for filter refiner and dtree with specific methods.
And then provide required values to `EnumAttribute` as props (see `components/numeric-condition`)

2022-05-18 22:59 UTC, AndreyUstyumenko approved these changes

2022-05-20 08:35 UTC, QYaroslavTrefilov approved these changes

2022-05-20 13:58 UTC, merged