(FOROME-1202) Refactoring Test cases for Locus
ForomePlatform/Anfisa-React-Client pull request #723
Opened 2022-06-10 11:39 UTC by OtarGigolashvili

https://quantori.atlassian.net/browse/FOROME-1202

2022-06-10 11:44 UTC, Mariamkikalia approved these changes

2022-06-14 06:48 UTC, mbredeleva requested changes

2022-06-14 06:48 UTC, mbredeleva commented on qa/tests/features/filter-refiner/func-attributes/locus.feature
> +	And clicks the "Apply"
clicks the "Apply" button

2022-06-14 09:36 UTC, OtarGigolashvili commented on qa/tests/features/filter-refiner/func-attributes/locus.feature
> +	And clicks the "Apply"
Changed in new commit

2022-06-14 09:40 UTC, mbredeleva approved these changes

2022-06-14 10:19 UTC, merged