(FOROME-1196) Updated "list-value-attr-filter" test cases
ForomePlatform/Anfisa-React-Client pull request #727
Opened 2022-06-10 16:14 UTC by Mariamkikalia

https://quantori.atlassian.net/browse/FOROME-1196

2022-06-13 11:45 UTC, Gjeriashvili approved these changes

2022-06-14 06:46 UTC, mbredeleva requested changes

2022-06-14 06:46 UTC, mbredeleva commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
was open -> was opened

2022-06-14 06:46 UTC, mbredeleva commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
was open -> was opened

2022-06-14 06:46 UTC, mbredeleva commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
the same ))

2022-06-14 06:46 UTC, mbredeleva commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
the same here and below

2022-06-14 09:55 UTC, Mariamkikalia commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
Done

2022-06-14 09:55 UTC, Mariamkikalia commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
Done

2022-06-14 09:55 UTC, Mariamkikalia commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
Done

2022-06-14 09:55 UTC, Mariamkikalia commented on qa/tests/features/filter-refiner/list-value-attr-filter.feature
> +		Given the "Filter Refiner" for the "xl_PGP3140_wgs_NIST-4_2" was open
Done

2022-06-16 08:13 UTC, mbredeleva approved these changes

2022-06-16 08:17 UTC, merged