(FOROME-1242) Updated "Drawer" test cases
ForomePlatform/Anfisa-React-Client pull request #743
Opened 2022-06-16 10:22 UTC by Mariamkikalia

Jira task: https://quantori.atlassian.net/browse/FOROME-1242

2022-06-16 11:39 UTC, OtarGigolashvili approved these changes

2022-06-16 12:45 UTC, Gjeriashvili approved these changes

2022-06-16 13:43 UTC, mbredeleva requested changes

2022-06-16 13:43 UTC, mbredeleva commented on qa/tests/features/main-table/drawer.feature
> +Scenario: 01 Open URL
There are several other links in drawer, for example, "open igv" etc. Why only a "gnomAD Browser" is checked here?

2022-06-16 13:43 UTC, mbredeleva commented on qa/tests/features/main-table/drawer.feature
>  Feature: Main table, Drawer
Please, add a case "user deletes a tag"

2022-06-21 10:30 UTC, Mariamkikalia commented on qa/tests/features/main-table/drawer.feature
>  Feature: Main table, Drawer
Done.

2022-06-21 14:15 UTC, mbredeleva approved these changes

2022-06-21 14:17 UTC, merged