Fix/forome 1236
ForomePlatform/Anfisa-React-Client pull request #753
Opened 2022-06-21 08:13 UTC by EvgeniySobolev

[Task](https://quantori.atlassian.net/browse/FOROME-1236)

2022-06-21 11:15 UTC, AlMaQntr requested changes

2022-06-21 11:15 UTC, AlMaQntr commented on src/pages/main/components/sidebar/datasets-list/components/dataset-name.tsx
> +  useEffect(() => {
I think it's better to decide whether a tooltip is needed is to check that text doesn't fit into container.
container.clientWidth would be less than container.scrollWidth if text doesn't fit into container with overflow: hidden

2022-06-21 11:15 UTC, AlMaQntr commented on src/pages/main/components/sidebar/datasets-list/components/dataset-name.tsx
> +  useEffect(() => {
Please, try to use it

2022-06-21 17:15 UTC, AndreyUstyumenko approved these changes

2022-06-22 04:06 UTC, AlMaQntr approved these changes

2022-06-22 04:10 UTC, merged