fix(FOROME-1280): enum modals and panels height
ForomePlatform/Anfisa-React-Client pull request #770
Opened 2022-06-27 11:15 UTC by Lapk1n

https://quantori.atlassian.net/browse/FOROME-1280

2022-06-27 12:00 UTC, AndreyUstyumenko approved these changes

2022-06-27 13:29 UTC, QSdmitrioul requested changes

2022-06-27 13:29 UTC, QSdmitrioul commented on src/pages/filter/refiner/components/middle-column/panels/enum-panel/enum-panel.tsx
> +    enumVariants.length > DEFAULT_COUNT ? 'calc(500px - 249px)' : 'auto'
There should be 100% instead of 500px

2022-06-28 05:44 UTC, Lapk1n commented on src/pages/filter/refiner/components/middle-column/panels/enum-panel/enum-panel.tsx
> +    enumVariants.length > DEFAULT_COUNT ? 'calc(500px - 249px)' : 'auto'
Thanks

2022-06-28 11:58 UTC, QSdmitrioul approved these changes

2022-06-29 10:09 UTC, merged