add table virtualization
ForomePlatform/Anfisa-React-Client pull request #78
Opened 2021-06-29 16:29 UTC by Ellerage

2021-06-29 18:24 UTC, Hellek requested changes

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/cell-filter.tsx
> +      style={{ width: 100, overflowWrap: 'break-word', wordBreak: 'break-all' }}
Для часто повторяемых элементов рекомендуют использовать css- классы, отрисовка быстрей идёт. Табличные ячейки это как раз та самая история

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/table-variants.tsx
> +  & * {
* - довольно тяжелый селектор для ререндеринга, а на этой странице из-за виртуализации будет очень много ререндеринга отдельных блоков. Может лучше вручную более специфичные селекторы прописать?

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/table-variants.tsx
> +          font-size: 12px;
В макете вроде 14 шрифт сейчас

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/table.tsx
> +    const [ref, setRef] = useState<any>(null)
А useRef тут не лучше подойдёт?

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/table.tsx
> +          <div
Т.е. по факту это не таблица будет, а div с поведением таблицы?

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/table.tsx
> +              'cursor-pointer',
'tr cursor-pointer flex items-center' - если не планируется в ближайшее время добавление условий, то в 1 строку мне кажется это может чуть быстрее отрабатывать. И иногда так читается легче

2021-06-29 18:24 UTC, Hellek commented on src/pages/ws/ui/table.tsx
> +        <div className="text-black thead">
text-black - по умолчанию наследуется от html, тут не нужно

2021-06-29 18:24 UTC, Hellek commented on src/ui/popper-button.tsx
> +          style={{ ...styles.popper, zIndex: 1000 }}
Может быть лучше через класс https://tailwindcss.com/docs/z-index ?

2021-06-30 11:41 UTC, Ellerage commented on src/ui/popper-button.tsx
> +          style={{ ...styles.popper, zIndex: 1000 }}
Не работает, через класс

2021-06-30 11:42 UTC, Ellerage commented on src/pages/ws/ui/table.tsx
> +          <div
Да, если делать через таблицу то ошибки будут, к тому же в документации, так и реализовано

2021-06-30 11:43 UTC, Ellerage commented on src/pages/ws/ui/table.tsx
> +    const [ref, setRef] = useState<any>(null)
По сути это не ref на элемент, а объект с свойствами таблицы. Я пробовал через useRef, но так не работает

2021-06-30 13:14 UTC, merged