(FOROME-1318) updated "Decision Tree Panel" test cases
ForomePlatform/Anfisa-React-Client pull request #805
Opened 2022-07-11 11:41 UTC by Mariamkikalia

Task on Jira - https://quantori.atlassian.net/browse/FOROME-1318

2022-07-11 13:07 UTC, Gjeriashvili approved these changes

2022-07-13 10:34 UTC, mbredeleva requested changes

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/attribute-dialog/attribute-dialog.feature
> +	Scenario: 01 Open "Decision Tree Panel"
If the folder is "attribute-dialog", only scenarios that relates to attribute dialog should be here. This scenario doesn't relate.

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/attribute-dialog/attribute-dialog.feature
> +		Given the "Decision Tree Panel" was opened for the "xl_PGP3140_wgs_NIST-4_2" dataset
Gerkin syntax allows to use "Background" keyword if you have for common precondition in all scenarios in feature file. Here it is 
> Given the "Decision Tree Panel" was opened for the "xl_PGP3140_wgs_NIST-4_2" dataset
> And the attribute dialog was opened via "+ Add Attribute" button

See https://cucumber.io/docs/gherkin/reference/#background
BUT
Better to use active voice, not passive. Describe an action and an actor: user opens page, user clicks button.
Notice, using "background" you can edit it only once ))

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/attribute-dialog/attribute-dialog.feature
> +		Then all values should be checked
"all values should be checked" -> "all checkboxes should be checked"
These elements are checkboxes

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/attribute-dialog/attribute-dialog.feature
> +		Then all selected values should be unchecked
all checkboxes should be unchecked

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/attribute-dialog/attribute-dialog.feature
> +	Scenario: 10 Collapse one group
Should scenarios 10, 11 and 12 be in regression list?

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/charts/charts.feature
> +		Then the field should be filtered
maybe better "empty result is shown"? Or you can jest merge this scenario with 01

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/charts/charts.feature
> +		Given the "Decision Tree Panel" was opened
You can also use "Background" in this feature

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/charts/charts.feature
> +		Then the filters should be added
It looks like here the number of found variants needed to ensure that join works correctly here and in scenarios 7-9

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/charts/charts.feature
> +	Scenario: 12 Collapse all groups in charts
Should this scenarios be in regression list? If it was broken it would be a low-priority bug

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +		Given the "Decision Tree Panel" for the "xl_PGP3140_wgs_NIST-4_2" was opened
Background ))

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +	Scenario: 05 Create new Decision Tree with empty name
Are scenarios 5-7 regression?

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +		Given custom Decision Tree was added to Decision Tree
First, the "Decision Tree Panel" was opened.
Then, custom Decision Tree should exist in the system
Does "was added" mean that custom ds was selected in "Select Decision tree" drop-down? (Scenarios 8-12)
Here you use "was added", one can understand it like "was added in the system". In dataset creation scenarios you wrote "was loaded". "Was loaded" is better

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +		And clicks "Decision Tree" drop-down
"Select Decision tree" drop-down. Here and below

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +	Scenario: 09 Cancel custom Decision Tree modification
9, 10, 12 are low-priority checks. They shouldn't be in regression check list

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +		And no changes were made
So you can just remove this string ))

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/create-decision-tree/create-decision-tree.feature
> +  As the Anfisa user I want to create custom decision trees and be able to modify and delete them
tab

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +  As the Anfisa user I want to create new datasets on the "Decision Tree Panel" page
tab

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +		Given the "Decision Tree Panel" for the "xl_PGP3140_wgs_NIST-4_2" dataset was opened
Background

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +	Scenario: 01 Create dataset: empty name
The first scenario should be success case, the happy path.

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +	Scenario: 03 Create dataset: long name
Scenarios 3-6 can be united in one "Create dataset: incorrect name"

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +	Scenario: 08 Cancel dataset creation
It's can be removed from regression

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +		Then dataset should be saved
And message in buttom right corner should be displayed

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +		Then dataset creation should not be canceled
Better
Then dataset should be saved
And message in buttom right corner should be displayed
"should not be canceled" is too blurry

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +	Scenario: 09 Close Create Dataset dialog during creation
looks like it's not regression case too

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +	Scenario Outline: 10 Save Dataset with more than 2000 Variants
Why 2000?

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +  As the Anfisa user I want to edit a decision tree via Text Editor dialog
tab

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +		Given the "Decision Tree Panel" for XL dataset was opened
Background

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +		When user adds an additional valid attribute condition value manually
Input string is needed here

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +		And changes should be saved locally
"Saved locally" means saved in text editor but not saved in the medium section? Please write more detailed: "user sees changes here and can't see there..."

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +		Then <New Value> should be added to the tree
to the tree -> in the Algorithm section

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +	Scenario: 11 Saving with invalid boolean value (True, False)
11, 12 - not a regression case

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/text-editor/text-editor.feature
> +	Scenario: 17 Copy 100 rows
Why 100? Are there any restrictions for condition number?

2022-07-13 10:34 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/tree/tree.feature
> +  As the Anfisa user I want to see the Decision Trees list on the "Decision Tree Panel" page
tab

2022-07-27 10:18 UTC, mbredeleva requested changes

2022-07-27 10:18 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/charts/charts.feature
> +	| ValidNameField |
InvalidNameField ))

2022-07-27 10:18 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/dataset-creation/dataset-creation.feature
> +	Then dataset should be created
You should check also that you can open created dataset with "Open it" button and that created dataset has the correct number of variants.

2022-07-27 10:18 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/tree/tree.feature
> +	| ValidNameField |
InvalidNameField ))

2022-07-27 10:18 UTC, mbredeleva commented on qa/tests/features/new/manual/decision-tree/tree/tree.feature
> +Examples:
You have only one variable value. It can be a usual scenario, not a scenario outline

2022-07-27 11:57 UTC, mbredeleva approved these changes

2022-07-28 04:57 UTC, merged