(FOROME-1317) Test cases for Filter Refiner
ForomePlatform/Anfisa-React-Client pull request #827
Opened 2022-07-20 08:00 UTC by OtarGigolashvili

Task in Jira : https://quantori.atlassian.net/browse/FOROME-1317

2022-07-22 13:16 UTC, mbredeleva requested changes

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Attribute Search/Filter Refiner-Attribute Search.feature
> +Background:
Background is a common _GIVEN_ block for all scenarios. There can't be When or Then lines
Here it should be:
Given: User opens "Filter refiner" page for "xl_PGP3140_wgs_NIST-4_2" dataset
It can be opened by direct link without Main Page, "Open" dropdown etc. and nothing changes
What you wrote in Background is a correct test scenario for Main Page, not for Filter Refiner ))

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Attribute Search/Filter Refiner-Attribute Search.feature
> +Scenario Outline: 01 Search attribute name by existed value
Add variable ValidNameField in the scenario name (to make three runs of scenario differ in report). Here and below

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Attribute Search/Filter Refiner-Attribute Search.feature
> +	When user inputs <ValidNameField> in the search field
Use quotes for elements names (buttons, fields, pages, panels). Here: in the "Search" field on the left panel. Here and below

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Het/Filter Refiner-Compound_Het.feature
> +Scenario Outline: 01 Secondary dataset
I'd call this scenario "01 Filtering by Compound_Het Value* in WS dataset"
* "Compound_Het Value" should be in corner brackets. Git doesn't allow to use them in comment

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Het/Filter Refiner-Compound_Het.feature
> +	And selects the <Compound Het_Value> in the drop-down
Compound_Het Value. The name of the value should be correct. Here and below

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Het/Filter Refiner-Compound_Het.feature
> +	And "Compound_Het" Functional attribute was displayed
better
And user clicks "+" button near Functional Units
And selects "Compound_het" functional attribute
because user can't open the "Compound_Het" by direct link, only by clicking there
Here and below

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Het/Filter Refiner-Compound_Het.feature
> +	And clicks on  "Clear" button
Isn't it enough to write
Then "Not" check-box is discarded?

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Het/Filter Refiner-Compound_Het.feature
> +	Then Compound_Het should be added to the right part of the page
And it has "not" flag 
![image](https://user-images.githubusercontent.com/106255163/179953916-b66ea3b9-b6a8-4877-bebd-98b9aff2c480.png)

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Het/Filter Refiner-Compound_Het.feature
> +	Then the approx drop-down should be disabled
quotes

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Request/Filter Refiner-Compound_Request.feature
> +	And "Compound_Request" functional attribute was displayed
See comments to Compound_Het. Better:
And user clicks on "+" button near functional Units
And selects "Compound_Request" functional attribute
Here and below

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Request/Filter Refiner-Compound_Request.feature
> +	And enters "500" in the "Minimal count of events" input
500 or 10?

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Request/Filter Refiner-Compound_Request.feature
> +	And selects "Homozygous Recessive / X-Linked" check-box
And clicks "Add" button?

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Compound_Request/Filter Refiner-Compound_Request.feature
> +	And enters "1" in the "Minimal count of events" input
The label on the form near this field is "scenario". Better to call the input "Scenario" here

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Attribute Search/Filter Refiner-Attribute Search.feature
> +@smoke
Should all these scenarios be smoke?

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Create Dataset/Filter Refiner-Create Dataset.feature
> +@smoke
Put an empty line between feature name and tags of first scenario

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Create Dataset/Filter Refiner-Create Dataset.feature
> +Scenario: 01 Open filter refiner for Secondary dataset
This is a scenario for main page, not for filter refiner

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Create Dataset/Filter Refiner-Create Dataset.feature
> +Scenario: 02 Create dataset: empty name
First scenario should be happy path, and after that - validation of different errors

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Create Dataset/Filter Refiner-Create Dataset.feature
> +Scenario: 04  Create dataset: long name
You can unite scenarios 4-7 in a single scenario outline "Create dataset with invalid name" and a table of examples

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Create Dataset/Filter Refiner-Create Dataset.feature
> +
Remove everything down

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Custom_Inheritance_Mode/Filter Refiner-Custom_Inheritance_Mode.feature
> +@smoke
Add empty line above tag

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Custom_Inheritance_Mode/Filter Refiner-Custom_Inheritance_Mode.feature
> +	Given The "Custom_Inheritance_Mode" functional attribute was displayed
Here you start with condition that functional attribute panel is displayed. But you don't write which dataset is selected.
Move 
`Given the Filter Refiner for the "xl_PGP3140_wgs_NIST-4_2" dataset was opened`
to Background section and add description how user opens the panel:
Given user clicks on "+" button near functional Units
And selects "Custom_Inheritance_Mode" functional attribute

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Custom_Inheritance_Mode/Filter Refiner-Custom_Inheritance_Mode.feature
> +Scenario: 02 The "Reset" value equals "Homozygous/X-linked"
What means "The "Reset" value equals "Homozygous/X-linked"" 
Maybe Inheritance mode value equals "Homozygous/X-linked"?
Here and below

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Custom_Inheritance_Mode/Filter Refiner-Custom_Inheritance_Mode.feature
> +	Then "Scenario" values should be HG002=2, HG003=0-1, HG004=0-1
I think the first check in then section should be that Custom_Inheritance_Mode block was added to "Results" panel and after that
And "Scenario" values in the block should be HG002=2, HG003=0-1, HG004=0-1
And the number of variants should be equal to "227768"

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Custom_Inheritance_Mode/Filter Refiner-Custom_Inheritance_Mode.feature
> +	Then number of variants should be equal to "5548058".
And Custom_Inheritance_Mode block on Results panel has "not" label

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Custom_Inheritance_Mode/Filter Refiner-Custom_Inheritance_Mode.feature
> +Scenario: 06 Clear button
Better to move the Result panel functionality (clear all, copy, edit and delete block) in separate feature file
And there is a clear button on Custom_Inheritance_Mode panel that you can test in this feature file 
![image](https://user-images.githubusercontent.com/106255163/180166234-fac5391d-8e1f-4199-a194-1651d8e34e38.png)

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filter Refiner-Pagination.feature
> +Background:
Just "user opens filter refiner for dataset  xl_PGP3140_wgs_NIST-4_2

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filtration/Filter Refiner-Filtration.feature
> +	And number of variants equal to <Number without All>
It's a check, it should be "Then" string, not "And". Better to divide this scenario

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filtration/Filter Refiner-Filtration.feature
> +	Then the user should not be able to check both of them at the same time
Better to describe user's actions. For example "When user selects check-box "CheckBoxOne", the check-box "CheckBoxTwo" is disabled"

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filtration/Filter Refiner-Filtration.feature
> +	And the variants should be filtered by <Attribute Value>
"The variants should be filtered" is not a clear phrase. What means that variants are filtered? Attribute name is shown in the results panel, number of variants changes, anything else?

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filtration/Filter Refiner-Filtration.feature
> +	And the "View variants" dialog can be opened
Move "View Variants" button check to another scenario

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filtration/Filter Refiner-Filtration.feature
> +	And the "Full list" radio-button should be disabled if number of variants > 300
Here behavior changed. For less then 300 variants Main Table opens, not "View variants" dialogue

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Filtration/Filter Refiner-Filtration.feature
> +Scenario Outline: 11 Remove all attribute values from the filter - Delete button case
I suggested earlier to move functionality of the "Results" panel (update attribute, delete it, clear all, copy, expand, collapse and others) to a separate feature file

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/GeneRegion/Filter Refiner-GeneRegion.feature
> +	| chr1:65058247 | 0              |
Add empty string under this string

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/GeneRegion/Filter Refiner-GeneRegion.feature
> +	And selects Filter Refiner
Just "Open "Filter refiner" page for "PGP3140_wgs_panel_hl" dataset"

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/GeneRegion/Filter Refiner-GeneRegion.feature
> +	And variants list should be filtered
Describe the checks more strict, please. The "GeneRegion" block is displayed on "Results" panel, "not" label is displayed, and so on

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +Background: Select Inheritance_Mode for XL dataset
Background can contain only Given and And strings

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +	When doesn't selects any problem group check-box
When user doesn't

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +	And clicks the "+ Add Attribute" button
He can't click because the button is disabled. Just remove this string

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +Scenario Outline: 08 Filter by Inheritance Modes for Secondary dataset
xl_PGP3140_wgs_NIST-4_2 (XL) was selected in background.

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +	And clicks on "+ Add Attribute" button
Is this step important? You needn't add attribute to clear the filter

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +	Then <Problem Group> should be selected
After user clicks on "Clear" button it's not

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Inheritance_mode/Filter Refiner-Inheritance_Mode.feature
> +Scenario: 12 Reset
***It looks like "Reset" and "Clear" button works similar

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Range Filter/Filter Refiner-Range Filter.feature
> +	When user clicks on "xl_PGP3140_wgs_NIST-4_2" dataset
There can be only Given and And steps in Background
Here you can use just
Given "Filter Refiner" page for the "xl_PGP3140_wgs_NIST-4_2" dataset was opened

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Range Filter/Filter Refiner-Range Filter.feature
> +	Then filter should be applied
Use more strict conditions, what user sees

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Range Filter/Filter Refiner-Range Filter.feature
> +	And the "Full List" view should be disabled
It should be another case in another feature file

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Range Filter/Filter Refiner-Range Filter.feature
> +Scenario Outline: 02 Filter by range, boundary values - XL dataset
Add please another case: when user doesn't input left or right value it is counted as minimum for the left value and maximum for the right

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Range Filter/Filter Refiner-Range Filter.feature
> +	| Num_Samples    | 1             | 2             | 3281689        |
Add please scenario that when user inputs values of an interval it is displayed on the diagram

2022-07-22 13:16 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/View/Filter Refiner-View.feature
> +
Add cases that check different types of diagrams for filters
![image](https://user-images.githubusercontent.com/106255163/180446840-dbe6e5c0-e7d3-4219-9f6a-9eb8d3854906.png)

2022-08-05 12:35 UTC, Mariamkikalia approved these changes

2022-08-08 11:19 UTC, mbredeleva approved these changes

2022-08-08 11:19 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Range Filter/Filter Refiner-Range Filter.feature
> +	And the range <Minimum Value> <= <Attribute Name> <= <Maximum Value> should be displayed in the right part of the screen
It's a bloody mess of brackets ))
I think better to use text "greater" or "greater or equals", because math signs are mixing with variables

2022-08-08 11:19 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Diagram/Diagram.feature
> +| Canonical_Annotation | 18                |
***Please add starting tabulation for lines inside "Examples" table to make the text more readable

2022-08-08 11:19 UTC, mbredeleva commented on qa/tests/features/new/manual/filter-refiner/Diagram/Diagram.feature
> +
*** Use one empty string before scenario

2022-08-09 10:00 UTC, merged