feat(FOROME-1367): made create derived dataset button disabled on empty conditions or too much variants exist
ForomePlatform/Anfisa-React-Client pull request #831
Opened 2022-07-20 11:38 UTC by QSdmitrioul

[Task](https://quantori.atlassian.net/browse/FOROME-1367)
In ControlPanel we check only filters, because it is used only in ws page, which can be opened only if we have less than 3000 variants.

2022-07-22 06:16 UTC, EvgeniySobolev approved these changes

2022-07-22 07:58 UTC, Lapk1n commented
1. Open ws ds in FR (create disabled)
2. Open some enum attr and just select some attr (create enabled)

1. Open xl_PGP3140_wgs_NIST-4_2 in the same page
2. Add Callers/GATK_HOMOZYGOUS (2112) variants were added
3. Create disabled

2022-07-22 13:06 UTC, AndreyUstyumenko commented
Something is wrong with user scenarios:
**WS**
1) Go to filter refiner on WS dataset. Create DS button is disable (OK)
2) Pick some attribute. The button goes enabled (NOT OK since we didn't make any change to the result yet)
3) Apply the criterium. The button goes disabled again (NOT OK since it's the very moment we'd like to create a derived DS)

**XL**
1) Go to filter refiner on XL dataset. Create DS button is disabled (OK)
2) Pick some attributes to shrink down the number of variants below 9000. Nothing happens to the button. (it is totally OK, but much different from the same logic on a WS dataset)
3) Apply the attributes. The button is still disabled (NOT OK)

The same picture we see on decision tree.

2022-07-22 13:10 UTC, AndreyUstyumenko requested changes
Something is wrong with user scenarios:

**WS**
1) Go to filter refiner on WS dataset. Create DS button is disable (**OK**)
2) Pick some attribute. The button goes enabled (**NOT OK** since we didn't make any change to the result yet)
3) Apply the criterium. The button goes disabled again (**NOT OK** since it's the very moment we'd like to create a derived DS)

**XL**
1) Go to filter refiner on XL dataset. Create DS button is disabled (**OK**)
2) Pick some attributes to shrink down the number of variants below 9000. Nothing happens to the button. (it is totally **OK**, but much different from the same logic on a WS dataset)
3) Apply the attributes. The button is still disabled (**NOT OK**)

The same picture we see on decision tree.

2022-07-27 12:40 UTC, QSdmitrioul commented
Fixed issues

2022-07-28 08:06 UTC, EvgeniySobolev approved these changes

2022-07-28 08:06 UTC, EvgeniySobolev commented on src/pages/filter/dtree/dtree.page.tsx
> +            dtreeStore.totalFilteredCounts.accepted > XL_COUNT_OF_VARIANTS
You could join last 2 conditions like `dtreeStore.totalFilteredCounts?.accepted > XL_COUNT_OF_VARIANTS`
Also I suggest to move long conditions to a variables

2022-07-28 08:06 UTC, EvgeniySobolev commented on src/pages/filter/refiner/refiner.page.tsx
> +          filterCounts.variants > XL_COUNT_OF_VARIANTS
It could be shortened too
`filterStore.conditions.length === 0 ||
filterCounts?.variants > XL_COUNT_OF_VARIANTS`

2022-07-29 12:57 UTC, AndreyUstyumenko commented on src/pages/filter/refiner/refiner.page.tsx
> +          filterCounts.variants > XL_COUNT_OF_VARIANTS
`!filterCounts` gives a truthy value if `filterCounts` is undefined
`filterCounts?.variants` gives a falsy value if `filterCounts` is undefined
They're not on the same level.

2022-07-29 13:02 UTC, AndreyUstyumenko approved these changes

2022-07-29 14:29 UTC, merged