feat(FOROME-1388): add default preset
ForomePlatform/Anfisa-React-Client pull request #837
Opened 2022-07-21 15:17 UTC by Lapk1n

https://quantori.atlassian.net/browse/FOROME-1388

2022-07-22 06:10 UTC, EvgeniySobolev approved these changes

2022-07-22 06:26 UTC, QSdmitrioul approved these changes

2022-07-22 13:42 UTC, AndreyUstyumenko requested changes
After reloading the page, preset switches to List, however Preset1 is selected in the menu
<img width="831" alt="Screen Shot 2022-07-22 at 16 41 59" src="https://user-images.githubusercontent.com/96476703/180451742-1f9ab384-375c-4416-99ba-3b8bcc32d357.png">

2022-07-22 14:04 UTC, AndreyUstyumenko commented on src/pages/ws/ui/variant-drawer/variant-drawer.data.ts
> +    name: 'Preset 1',
Let's call it more fancy. For example, Cards View

2022-07-22 14:12 UTC, AndreyUstyumenko commented on src/pages/ws/ui/variant-drawer/variant-drawer.store.ts
>          this.currentGridLayout = cloneDeep(preset.layout)
maybe just `this.currentGridLayout = preset.layout ? cloneDeep(preset.layout) : []` without ifs and the switch case block?

2022-07-26 20:27 UTC, AndreyUstyumenko commented
Preset is still getting reset when reloading. I think it should keep memorizing it across page reloads, it's pretty annoying.

2022-07-26 20:28 UTC, AndreyUstyumenko requested changes
Preset is still getting reset after reloading. I think it should keep it across page reloads, it's pretty annoying.

2022-08-10 10:21 UTC, AndreyUstyumenko approved these changes

2022-08-11 06:39 UTC, merged