fix(FOROME-1407): remove useless unfold icons
ForomePlatform/Anfisa-React-Client pull request #849
Opened 2022-07-28 07:23 UTC by EvgeniySobolev

[https://quantori.atlassian.net/browse/FOROME-1407](https://quantori.atlassian.net/browse/FOROME-1407)

2022-07-28 10:16 UTC, QSdmitrioul approved these changes

2022-07-29 12:39 UTC, AndreyUstyumenko approved these changes, later dismissed

2022-07-29 12:45 UTC, AndreyUstyumenko commented
Click on an attribute that doesn't have prediction power icon. Error boundary page appears.

2022-07-29 12:45 UTC, AndreyUstyumenko requested changes
Click on an attribute that doesn't have prediction power icon. Error boundary page appears.

2022-08-02 08:14 UTC, AndreyUstyumenko approved these changes

2022-08-02 10:48 UTC, merged