fix(FOROME-1408): increase clickable area for dropdown arrow
ForomePlatform/Anfisa-React-Client pull request #852
Opened 2022-07-29 05:05 UTC by EvgeniySobolev

[https://quantori.atlassian.net/browse/FOROME-1408](https://quantori.atlassian.net/browse/FOROME-1408)

2022-07-29 06:03 UTC, Lapk1n requested changes
<img width="454" alt="Screenshot 2022-07-29 at 10 00 19" src="https://user-images.githubusercontent.com/74919871/181693100-869e696e-e87f-4046-9425-20f3cc9f5ea7.png">
When the mouse enters this zone, an arrow becomes active

2022-08-01 07:23 UTC, Lapk1n approved these changes

2022-08-02 09:12 UTC, AndreyUstyumenko commented
remove hover state from the title, it gets hovered the icon but it's not clickable
<img width="586" alt="Screen Shot 2022-08-02 at 12 11 15" src="https://user-images.githubusercontent.com/96476703/182338575-b3e28eee-9351-4518-82a0-4d106b9ef8d8.png">

2022-08-02 09:15 UTC, AndreyUstyumenko approved these changes

2022-08-02 10:38 UTC, merged